version: '3.5'

services:
  mongodb:
    image: mongo
    # volumes:
    #   - ./database:/data/db
    ports:
      - '27016:27017'
    networks: 
      - portal

  todo:
    image: todo
    build: .
    # volumes:
    #   - .:/usr/src/app
    depends_on:
      - mongodb
    ports:
      - "6789:6789"
    networks: 
      - portal
    external_links:
      # Links to shared containers
      - shared_db_1:sessiondb


networks: 
  portal:
    external: true
    name: portal 
    